# Generated by Django 3.1.4 on 2022-10-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alokairu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrikula', models.CharField(max_length=7)),
                ('marka', models.CharField(max_length=255)),
                ('modeloa', models.CharField(max_length=255)),
                ('urtea', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='pertsona',
            name='jaiotzeData',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='KotxeaPertsona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alokairuData', models.CharField(max_length=10)),
                ('dniPertsona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alokairu.pertsona')),
                ('matrikula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alokairu.kotxea')),
            ],
        ),
    ]
